/* @flow */
module.exports = {
  homePageIcon: require('./images/homepage_icon.png'),
  profileIcon: require('./images/profile_icon.png'),
  messagingIcon: require('./images/messaging_icon.png'),
  bleeding_icon: require('./images/bleeding_icon.png'),
  cancel: require('./images/cancel.png'),
  facebook_icon: require('./images/facebook-icon.png'),
  google_plus_icon: require('./images/google-plus-icon.png'),
  infusion_icon: require('./images/infusion_icon.png'),
  left_arrow: require('./images/left-arrow.png'),
  running_icon: require('./images/running_icon.png'),
  running_man: require('./images/running_man.png'),
  blood_pressure: require('./images/blood_pressure.png'),
  cardiogram: require('./images/cardiogram.png'),
  heart_rate: require('./images/heart_rate.png'),
  footsteps: require('./images/footsteps.png'),
  runner: require('./images/runner.png'),
  running: require('./images/running.png'),
  stairs_forward: require('./images/stairs-forward.png'),
  stairs: require('./images/stairs.png'),
  step_heart: require('./images/step-heart.png'),
  face_03: require('./images/Face_03.png'),
  pulse: require('./images/pulse.png'),
  fill_03: require('./images/Fill_03.png'),
};
